### ISSUE TITLE
tv4play.se "ERROR: No videos found. Cant find video id for the video"

### ISSUE THREAD

**Issue by attrembl** [spaam/svtplay-dl#1543]
### svtplay-dl versions:

svtplay-dl 4.22

### Operating system and Python version:

Windows 11
C:\svtplay-dl>python --version
Python 3.10.11

### What is the issue:

C:\svtplay-dl>svtplay-dl --verbose -S https://www.tv4play.se/video/2251d08c71dba32c5c16

DEBUG [1686757937.8457625] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.22
DEBUG [1686757937.8467593] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1686757937.8472636] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/video/2251d08c71dba32c5c16'
DEBUG [1686757937.848297] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1686757938.811665] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/2251d08c71dba32c5c16 HTTP/1.1" 200 None

ERROR [1686757939.0289404] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Cant find video id for the video

**Comment by spaam** [comment]
yeah they made a bunch of changes.
to make it work like before with season and episode info and other metadata going to take time and im not sure when that going to happen.

**Comment by kingzcrown** [comment]
This is so sad. Is there really no way to fix this issue so we can dl from tv4 again?

**Comment by spaam** [comment]
@kingzcrown i dont get paid to do this , i enjoy doing other things on my spare time you know. it get prioritized after it. maybe it will get fixed later this week or next. 
a donation for a pizza will make things prioritized higher and fixed tonight :)

**Comment by kingzcrown** [comment]
@spaam LOL. That's okay, I can wait a week. Thank you for looking into it when you have the time. Maybe I could even sponsor you with a pizza. But I'm on a fixed budget, so it would have to be one of those cheap frozen ones from the grocery store. :)

**Comment by martinlindhe** [comment]
@spaam I sent some pizza cash your way <3

**Comment by spaam** [comment]
should be fixed now .) thanks for the donations <3

**Comment by Sopor** [comment]
I still can't download. Same error message as before.

```
svtplay-dl.exe https://www.tv4play.se/video/ed3d3d774f32a30db63b/hyllningskonsert-emil-i-l%C3%B6nneberga-60-%C3%A5r -v
DEBUG [1687098643.7506967] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.23
DEBUG [1687098643.7536862] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1687098643.7536862] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/video/ed3d3d774f32a30db63b/hyllningskonsert-emil-i-l%C3%B6nneberga-60-%C3%A5r'
DEBUG [1687098643.7557092] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1687098643.8807187] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/ed3d3d774f32a30db63b/hyllningskonsert-emil-i-l%C3%B6nneberga-60-%C3%A5r HTTP/1.1" 200 None
ERROR [1687098643.8896983] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found.
```

svtplay-dl 4.23

**Comment by spaam** [comment]
yeah you need username and password to download.   i guess i forgot about that error message

**Comment by Sopor** [comment]
After adding:
```
  tv4play:
    username: ************@********
    password: ************
```
to the `svtplay-dl.yaml` it is now working.

**Comment by spaam** [comment]
releasing 4.24 with a improved error message .)
