### ISSUE TITLE
Strange subtitle from SVTPlay

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#315]
When i download the subtitle look like this, but i do get subtitle if i run it from my web browser on SVTPlay so the text do exists.

```
$ svtplay-dl -S http://www.svtplay.se/video/5533426/froken-frimans-krig/froken-frimans-krig-sasong-2-avsnitt-1

#EXTM3U
#EXT-X-TARGETDURATION:30
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:30,	
00_00_00_00.vtt
#EXTINF:30,	
00_00_30_00.vtt
#EXTINF:30,	
00_01_00_00.vtt
#EXTINF:30,	
00_01_30_00.vtt
#EXTINF:30,	
00_02_00_00.vtt
#EXTINF:30,	
00_02_30_00.vtt
#EXTINF:30,	
00_03_00_00.vtt
#EXTINF:30,	
00_03_30_00.vtt
#EXTINF:30,	
00_04_00_00.vtt
#EXTINF:30,	
00_04_30_00.vtt
#EXTINF:30,	
00_05_00_00.vtt
#EXTINF:30,	
00_05_30_00.vtt
#EXTINF:30,	
00_06_00_00.vtt
#EXTINF:30,	
00_06_30_00.vtt
#EXTINF:30,	
00_07_00_00.vtt
#EXTINF:30,	
00_07_30_00.vtt
#EXTINF:30,	
00_08_00_00.vtt
#EXTINF:30,	
00_08_30_00.vtt
#EXTINF:30,	
00_09_00_00.vtt
#EXTINF:30,	
00_09_30_00.vtt
#EXTINF:30,	
00_10_00_00.vtt
#EXTINF:30,	
00_10_30_00.vtt
#EXTINF:30,	
00_11_00_00.vtt
#EXTINF:30,	
00_11_30_00.vtt
#EXTINF:30,	
00_12_00_00.vtt
#EXTINF:30,	
00_12_30_00.vtt
#EXTINF:30,	
00_13_00_00.vtt
#EXTINF:30,	
00_13_30_00.vtt
#EXTINF:30,	
00_14_00_00.vtt
#EXTINF:30,	
00_14_30_00.vtt
#EXTINF:30,	
00_15_00_00.vtt
#EXTINF:30,	
00_15_30_00.vtt
#EXTINF:30,	
00_16_00_00.vtt
#EXTINF:30,	
00_16_30_00.vtt
#EXTINF:30,	
00_17_00_00.vtt
#EXTINF:30,	
00_17_30_00.vtt
#EXTINF:30,	
00_18_00_00.vtt
#EXTINF:30,	
00_18_30_00.vtt
#EXTINF:30,	
00_19_00_00.vtt
#EXTINF:30,	
00_19_30_00.vtt
#EXTINF:30,	
00_20_00_00.vtt
#EXTINF:30,	
00_20_30_00.vtt
#EXTINF:30,	
00_21_00_00.vtt
#EXTINF:30,	
00_21_30_00.vtt
#EXTINF:30,	
00_22_00_00.vtt
#EXTINF:30,	
00_22_30_00.vtt
#EXTINF:30,	
00_23_00_00.vtt
#EXTINF:30,	
00_23_30_00.vtt
#EXTINF:30,	
00_24_00_00.vtt
#EXTINF:30,	
00_24_30_00.vtt
#EXTINF:30,	
00_25_00_00.vtt
#EXTINF:30,	
00_25_30_00.vtt
#EXTINF:30,	
00_26_00_00.vtt
#EXTINF:30,	
00_26_30_00.vtt
#EXTINF:30,	
00_27_00_00.vtt
#EXTINF:30,	
00_27_30_00.vtt
#EXTINF:30,	
00_28_00_00.vtt
#EXTINF:30,	
00_28_30_00.vtt
#EXTINF:30,	
00_29_00_00.vtt
#EXTINF:30,	
00_29_30_00.vtt
#EXTINF:30,	
00_30_00_00.vtt
#EXTINF:30,	
00_30_30_00.vtt
#EXTINF:30,	
00_31_00_00.vtt
#EXTINF:30,	
00_31_30_00.vtt
#EXTINF:30,	
00_32_00_00.vtt
#EXTINF:30,	
00_32_30_00.vtt
#EXTINF:30,	
00_33_00_00.vtt
#EXTINF:30,	
00_33_30_00.vtt
#EXTINF:30,	
00_34_00_00.vtt
#EXTINF:30,	
00_34_30_00.vtt
#EXTINF:30,	
00_35_00_00.vtt
#EXTINF:30,	
00_35_30_00.vtt
#EXTINF:30,	
00_36_00_00.vtt
#EXTINF:30,	
00_36_30_00.vtt
#EXTINF:30,	
00_37_00_00.vtt
#EXTINF:30,	
00_37_30_00.vtt
#EXTINF:30,	
00_38_00_00.vtt
#EXTINF:30,	
00_38_30_00.vtt
#EXTINF:30,	
00_39_00_00.vtt
#EXTINF:30,	
00_39_30_00.vtt
#EXTINF:30,	
00_40_00_00.vtt
#EXTINF:30,	
00_40_30_00.vtt
#EXTINF:30,	
00_41_00_00.vtt
#EXTINF:30,	
00_41_30_00.vtt
#EXTINF:30,	
00_42_00_00.vtt
#EXTINF:30,	
00_42_30_00.vtt
#EXTINF:30,	
00_43_00_00.vtt
#EXTINF:30,	
00_43_30_00.vtt
#EXTINF:30,	
00_44_00_00.vtt
#EXTINF:30,	
00_44_30_00.vtt
#EXTINF:30,	
00_45_00_00.vtt
#EXTINF:30,	
00_45_30_00.vtt
#EXTINF:30,	
00_46_00_00.vtt
#EXTINF:30,	
00_46_30_00.vtt
#EXTINF:30,	
00_47_00_00.vtt
#EXTINF:30,	
00_47_30_00.vtt
#EXTINF:30,	
00_48_00_00.vtt
#EXTINF:30,	
00_48_30_00.vtt
#EXTINF:30,	
00_49_00_00.vtt
#EXTINF:30,	
00_49_30_00.vtt
#EXTINF:30,	
00_50_00_00.vtt
#EXTINF:30,	
00_50_30_00.vtt
#EXTINF:30,	
00_51_00_00.vtt
#EXTINF:30,	
00_51_30_00.vtt
#EXTINF:30,	
00_52_00_00.vtt
#EXTINF:30,	
00_52_30_00.vtt
#EXTINF:30,	
00_53_00_00.vtt
#EXTINF:30,	
00_53_30_00.vtt
#EXTINF:30,	
00_54_00_00.vtt
#EXTINF:30,	
00_54_30_00.vtt
#EXTINF:30,	
00_55_00_00.vtt
#EXTINF:30,	
00_55_30_00.vtt
#EXTINF:30,	
00_56_00_00.vtt
#EXTINF:30,	
00_56_30_00.vtt
#EXTINF:30,	
00_57_00_00.vtt
#EXTINF:30,	
00_57_30_00.vtt
#EXTINF:30,	
00_58_00_00.vtt
#EXT-X-ENDLIST

```

**Comment by spaam** [comment]
yeah i got a report about this on IRC.  they have changed some stuff on their page.

**Comment by spaam** [comment]
this is fixed in master. svtplay have changed how their site works a bit. for example the video ids next to svtplay in the end have changed...

**Comment by einarblaberg** [comment]
It seems the problem still exists for some content (children only?) on SVT.
Examples:
http://www.svtplay.se/video/5674442/sara-och-anka/sara-och-anka-sasong-2-avsnitt-3
http://www.svtplay.se/video/1326591/lotta-pa-brakmakargatan/avsnitt-3
http://www.svtplay.se/video/1681130/daniel-tigers-kvarter/avsnitt-37

**Comment by spaam** [comment]
@einarblaberg are you using latest master or the release version?  the binary svtplay-dl in the repo is the 0.20.2015.11.29 ?

**Comment by Blobbel** [comment]
I am thinking the version could be the issue. The Sara&Anka one works here, version reports as 0.20.2015.11.29-16-g7c9f29f . Kvack!

```
raspberrypi:~> svtplay-dl -S --force-subtitle http://www.svtplay.se/video/5674442/sara-och-anka/sara-och-anka-sasong-2-avsnitt-3
INFO: Outfile: sara.och.anka.s02e03.avsnitt.3-a25d756-svtplay.srt
raspberrypi:~> head sara.och.anka.s02e03.avsnitt.3-a25d756-svtplay.srt
1
0:00:00,000 --> 0:00:02,880
Sara och Anka.

2
0:00:03,880 --> 0:00:06,320
Sara och Anka.

3
0:00:07,320 --> 0:00:10,000
raspberrypi:~> svtplay-dl --version
0.20.2015.11.29-16-g7c9f29f
raspberrypi:~>
```

**Comment by einarblaberg** [comment]
@spaam @Blobbel 
Sorry, my bad, didn't make after pull =(
Works as it should after clean clone and make.
