### ISSUE TITLE
--exclude does not seems to work

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#483]
When i try to use --exclude on viafree i can't get it to exclude any episodes.

```
svtplay-dl -A --exclude=s1 http://www.viafree.se/program/livsstil/lyxfallan
```

This will still download `lyxfallan.s1e2-3608-tv3play.ts` (there is no episode s1e1) and all the s1 episodes.

**Comment by spaam** [comment]
that is because of the naming is happen after the exclude.

**Comment by Sopor-** [comment]
If i try to download from viafree with `--exclude=s1` it will ignore the exclude and start to download. If i use `--exclude=s1,` it will skip all episodes, 6 from s1 and 3 from s2. I assume this is normal behavior if it won't work :)

svtplay-dl -A -S --exclude=s1 http://www.viafree.se/program/livsstil/skonhetsfallan
svtplay-dl -A -S --exclude=s1, http://www.viafree.se/program/livsstil/skonhetsfallan

**Comment by Sopor-** [comment]
Any ETA on this one?

**Comment by qnorsten** [comment]
I can try to take a look at it later today:) 
For now you can at least get only one season at a time by using a url like https://www.viafree.se/program/drama/black-widows/sasong-2/ or https://www.viafree.se/program/drama/black-widows/sasong-2/avsnitt-1

**Comment by qnorsten** [comment]
@Sopor-  https://github.com/spaam/svtplay-dl/commit/c762575038eb5c8c46abb141ababcb68becd61cd should fix the problem that --all-last gets the oldest episodes instead of the newest. 
I am working on a fix for exclude on viafree, but it is not 100 % done yet.

**Comment by qnorsten** [comment]
@Sopor-  this should work now:) Please try it and let me know if you experience any problems

**Comment by Sopor-** [comment]
I didn't know it worked on Viafree because the url won't change when changing seasons. It will still show `https://www.viafree.se/program/drama/black-widows`
and not
`https://www.viafree.se/program/drama/black-widows/sasong-2`
but then i know now :)

**Comment by qnorsten** [comment]
That functionality was introduced in https://github.com/spaam/svtplay-dl/commit/1dbe3155865e879bd7b96b3894f69bac329bdf96 as a response to https://github.com/spaam/svtplay-dl/issues/439 I guess it is not well documentated and a little bit unintuic as that url is never used on viaplay. But now --exclude also work as intended.

**Comment by selepo** [comment]
Should this be closed then, or do we need to update documentation first ?
