### ISSUE TITLE
SVTPlay - --exclude not working

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#542]
I have already reported that --exclude is not working on viafree #483 but now it seems to fail on SVTPlay too. Maybe it has to do with the last weeks changes on the SVTPlay site?
The title of the episode is: `Innan vi dör Säsong 1 - Avsnitt 3 - syntolkat`
```
svtplay-dl -A --exclude=syntolkat,teckensprakstolkat http://www.svtplay.se/innan-vi-dor
INFO: Outfile: innan.vi.dor.s01e03.avsnitt.3-3c63bf1-svtplay.srt
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: innan.vi.dor.s01e03.avsnitt.3-3c63bf1-svtplay.ts
[351/351][==============================================================================================================] ETA: 0:00:00
INFO: Outfile: innan.vi.dor.s01e03.avsnitt.3-5775b3c-svtplay.srt
INFO: Selected to download hls, bitrate: 2796
INFO: Outfile: innan.vi.dor.s01e03.avsnitt.3-5775b3c-svtplay.ts
[351/351][==============================================================================================================] ETA: 0:00:00
```
I'm running svtplay-dl 1.9.1

**Comment by spaam** [comment]
what name do you use in exclude ?  the one with ÅÄÖ or AAO or aao?

**Comment by spaam** [comment]
ah its there :D  it will download the syntolkat anyway? or what?

**Comment by spaam** [comment]
hmm

**Comment by spaam** [comment]
if the programVersionId  have an S at the end its syntolkad i guess.

**Comment by spaam** [comment]
T for teckentolkat.

**Comment by Sopor-** [comment]
I have always used `--exclude=syntolkat,teckensprakstolkat` but it has been changed?

**Comment by spaam** [comment]
@Sopor-  before it was in the filename. now they have moved it to some other place.

**Comment by qnorsten** [comment]
This should be solved in https://github.com/spaam/svtplay-dl/commit/de0fa8a715fe2ac3e9467e32803ef70b20b9902f

**Comment by Sopor-** [comment]
It seems that something is still not working when using --exclude. Even if i use s01 it will still download that episode and all the other. There should be an --include switch because you can see there are 172 episodes from season 01 to 22 so i need to exclude them all if i want to download only s22.
```
$ svtplay-dl -A -S --exclude=s01 https://www.viafree.se/program/livsstil/lyxfallan
INFO: Episode 1 of 172
INFO: Selected to download hls, bitrate: 1080
INFO: Outfile: lyxfallan.s01e03-3566-viafree.ts
[050/266][====================..........................................................................................] ETA: 0:00:36
```

**Comment by qnorsten** [comment]
@Sopor-  You are right that might be a good idea, 
For now I think you can use this url to only download season 22 
https://www.viafree.se/program/livsstil/lyxfallan/sasong-22
