### ISSUE TITLE
no space between words in subtitles

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#581]
When downloading subtitles sometimes there are no space between the words and i have found the reason. It will look like this in the SRT file: `I så fall måste&nbsp;du&nbsp;till sjukhus.` Could that be fixed?

**Comment by Sopor-** [comment]
It should be like this `I så fall måste <i>du</i> till sjukhus.`

**Comment by spaam** [comment]
url ?

**Comment by Sopor-** [comment]
`http://www.tv4play.se/program/macgyver-1986?video_id=3735853` but i have seen it in other episodes too. Open the srt file and goto 153

**Comment by qnorsten** [comment]
I think that commit should fix this.  Can you check with some other urls @Sopor-  and report if it works or not? I only tried with two different macgyver subtitles.

**Comment by Sopor-** [comment]
@qnorsten I don't know if i need to start a new issue but it will still show this text instead of a & sign
00:12:28,080 --> 00:12:31,880
Vi har fått låna henne
från Meier `&amp;` Ditzinger i Stockholm.

**Comment by qnorsten** [comment]
Det är ju enkelt att fixa med ännu en replace. Även om det kanske är smartare att kolla om det finns någon vettig inbygd python funktion som automatiskt avkodar alla html entities

**Comment by qnorsten** [comment]
@Sopor-  can you try if this fixes it https://github.com/qnorsten/svtplay-dl/commit/ccfaf327690471a6e10c08c6403f1323eaeaf777 ? In that case I will merge it in to the main project. I think it should do the trick.
