### ISSUE TITLE
"UnicodeDecodeError" when trying to download from SVTPlay

### ISSUE THREAD

**Issue by liedholmsimon** [spaam/svtplay-dl#711]
I'm trying to download a video from SVTPlay (I have a Mac OSX 10.12.6):

`svtplay-dl -S —verbose https://www.svtplay.se/video/15221073/vetenskapens-varld/vetenskapens-varld-sasong-27-den-stora-solformorkelsen-solar-eclipse`

But I get this error:
```Traceback (most recent call last):
File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 468, in main
get_multiple_media(urls, options)
File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 171, in get_multiple_media
get_media(url, copy.copy(options))
File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 174, in get_media
if "http" not in url[:4]:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

I'm not very tech-savvy, so I'm not sure what is going wrong. I downloaded another episode from SVTPlay less than a month ago using this code:
`svtplay-dl -S https://www.svtplay.se/video/14956844/vetenskapens-varld/vetenskapens-varld-sasong-27-avsnitt-2?start=auto` and it worked fine. Any ideas on how to fix this?

Regards,
Simon

**Comment by spaam** [comment]
try upgrading to 1.9.6 that you have in brew and see if you still get the error.

**Comment by liedholmsimon** [comment]
Thanks for the tip! Although I still get almost the same error message:

`Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 479, in main
    get_multiple_media(urls, options)
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 174, in get_multiple_media
    get_media(url, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 177, in get_media
    if "http" not in url[:4]:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)`

**Comment by spaam** [comment]
är detta all output du får från när du har med -v?  kan inte riktigt reproducera problemet.

**Comment by liedholmsimon** [comment]
Det funkar helt problemfritt nu, men bara efter att jag tagit _bort_ `-verbose`
Tusen tack för hjälpen!

**Comment by hinmat** [comment]
Hi, 
when I specify an output path I get 

"UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)" 

but when I drop the -o path it works great. Is it python config f*ckup on my part?

Running 1.9.3 on rasp pi 2.

----
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.9.3', u'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 464, in main
    get_media(urls[0], options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 194, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 316, in get_one_media
    stream.download()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/fetcher/dash.py", line 139, in download
    self._download2(self.audio, audio=True)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/fetcher/dash.py", line 188, in _download2
    file_d = output(copy.copy(self.options), "m4a")
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/output.py", line 163, in output
    findexpisode(os.path.dirname(os.path.realpath(options.output)), options.service, os.path.basename(options.output)):
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/output.py", line 193, in findexpisode
    files = [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

**Comment by spaam** [comment]
can you give us some example of output path that failed?

**Comment by hinmat** [comment]
svtplay-dl -o /mnt/NASty/Films/newSVT/ https://www.svtplay.se/video/15559153/mr-robot/mr-robot-sasong-3-avsnitt-1

**Comment by dalgr** [comment]
Fixed in: https://github.com/spaam/svtplay-dl/pull/717

**Comment by fiskhandlarn** [comment]
I'm still getting this on 1.9.10, but only when called remotely to my qnap nas:

```
/cygdrive/c/Program\ Files\ \(x86\)/plink.exe -ssh xxx@dyn.joelson.org -P xxx -pw xxx "cd /share/Video/_new/tv/; /opt/bin/python2.7 /opt/bin/svtplay-dl -S https://www.svtplay.se/video/17264522/vader/vader-8-mar-10-00-2"
```

outputs

**Comment by dalgr** [comment]
@fiskhandlarn 
Can you test with the code from this branch:
https://github.com/dalgr/svtplay-dl/commits/hls_output_decode_error

**Comment by fiskhandlarn** [comment]
@dalgr Sadly, no. When I run this command remotely:

```
/cygdrive/c/Program\ Files\ \(x86\)/plink.exe -ssh xxx@yyy.com -P xxx -pw xxx "cd /share/Video/_new/tv/; /opt/bin/python2.7 /share/CACHEDEV1_DATA/tmp/svtplay/svtplay-dl-hls_output_decode_error/bin/svtplay-dl -S https://www.svtplay.se/video/17264522/vader/vader-8-mar-10-00-2"
```

I get this:

```
INFO: Selected to download dash, bitrate: 2916
INFO: Outfile: vader.tor.8.mar.10.00-d836ede-svtplay.m4a
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/tmp/svtplay/svtplay-dl-hls_output_decode_error/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/opt/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 511, in main
    get_media(urls[0], options)
  File "/opt/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 217, in get_media
    get_one_media(stream, copy.copy(options))
  File "/opt/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 338, in get_one_media
    stream.download()
  File "/opt/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 195, in download
    self._download2(self.audio, audio=True)
  File "/opt/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 206, in _download2
    file_d = output(copy.copy(self.options), "m4a")
  File "/opt/lib/python2.7/site-packages/svtplay_dl/output.py", line 157, in output
    findexpisode(os.path.dirname(os.path.realpath(options.output)), options.service, os.path.basename(options.output)):
  File "/opt/lib/python2.7/site-packages/svtplay_dl/output.py", line 181, in findexpisode
    files = [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]
  File "/opt/lib/python2.7/posixpath.py", line 73, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 26: ordinal not in range(128)
```

Running it locally works though.

Maybe it's something wrong with my NAS? But on the other hand, the error message is similar to the ones people got above?

Should this be run with python2 btw? When I try python3 I get:

```
You need to install python-requests to use this script
```
